name: Expressions implementation 
on: push 
env: 
  appName: CounterApp 
 
jobs: 
  build_job: 
    runs-on: windows-latest 
    steps:
       - name: Cache 

      uses: actions/cache@v1.2.1 

      with: 

        # A directory to store and save the cache 

        path: . 

        # An explicit key for restoring and saving the cache 

        key: "artifact" 

        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key 

        restore-keys: "" # optional 

